var dictionary = {
        "en": {
            "login": "Login",
            "username": "Username",
			"language": "Language",
			"movies": "<b>MOVIES</b>",
			"title": "Storytelling Generator 1.4",
			"myname": "Create by Prof. Paulo Alceu Rezende - 2021/2026",
			"starwars": "Star Wars",
			"lordofrings": "LORD OF RINGS",
			"matrix": "MATRIX",
			"harrypotter": "HARRYPOTTER",
			"lionking": "LIONKING",
			"tail": "CREATE TAIL",
			"scenes": "<b>SCENES</b>",
			"references": "REFERENCES",
			"over": "OVER THE TOP",
			"realsteel": "REAL STEEL",
			"pointbreak": "POINT BREAK",
			"fastandfurious1":"FAST AND FURIOUS 1",
			"catjouney":"CAT JOURNEY",
			"herojouney":"HERO JOURNEY",
			"savethecat":"SAVE THE CAT",
			"act1":"ACT 1 (INITIAL AND CONFLICT)",
			"Smurfette":"Smurfette Effect (just a female protagonist)",
			"Class":"Class",
			"act2":"ACT 2 (DEVELOPMENT)",	
			"act3":"ACT 3 (CLIMAX)",	
			"act4":"ACT 4 (OUTCOME)",		
			"PLOTS_TYPES":"<b>PLOTS TYPES</b>",			
			"DUCKLING":"THE UNGLY DUCKLING",		
			"THEWIZARDOFOZ":"THE WIZARD OF OZ",		
			"NEMO":"FINDING NEMO",		
			"ALICE":"ALICE IN WONDERLAND",		
			"GULLIVERS":"GULLIVERS TRAVELS",		
			"PINOCCHIO":"PINOCCHIO",		
			"MIDSUMMER":"A MIDSUMMER NIGHTS DREAM",		
			"BRIDGET":"BRIDGET JONES DIARY",		 
			"MACBETH":"MACBETH",		
			"ROMEO":"Romeo and Juliet",		
			"BREAKING":"BREAKING BAD",		
			"SLEEPING":"SLEEPING BEAUTY",					
			"BEAST":"BEAUTY AND THE BEAST",		
			"MONSTER":"Overcome over Monster",		
			"MISERY":"From Misery to Wealth",		
			"ALICE":"Alice in Wonderland",		
			"Busca":"The Search",		
			"Viagem":"Trip and Return",		
			"KINGKONG":"King Kong",		
			"":"",		
			"":"",					
			"":"",		
			"":"",		
			"":"",		
			"":"",		
			"":"",		
			"":"",		
			"":"",		
			"":"",		
			"":"",					
			"":"",		
			"":"",		
			"":"",		
			"":"",		
			"":"",		
			"":"",		
			"":"",		
			"":"",		
			"":"",					
			"":"",		
			"":"",		
			"":"",		
			"":"",		
			"":"",		
			"":"",		
			"":"",		
			"":"",		
			"":"",					
			"":"",		
			"":"",		
			"":"",		
			"":"",		
			"":"",		
			"":"",		
			"":"",		
			"":"",		
			"":"",					
			"":"",		
			"":"",		
			"":"",		
			"":"",		
			"":"",		
			"":"",		
			"":"",		
			"":"",	
			"":"",					
			"":"",		
			"":"",		
			"":"",		
			"":"",		
			"":"",		
			"":"",		
			"":"",		
			"":"",		
			"":"",					
			"":"",		
			"":"",		
			"":"",		
			"":"",		
			"":"",		
			"":"",		
			"":"",		
			"":"",		
			"":"",					
			"":"",		
			"":"",		
			"":"",		
			"":"",		
			"":"",		
			"":"",		
			"":"",		
			"":"",	
			"":"",					
			"":"",		
			"":"",		
			"":"",		
			"":"",		
			"":"",		
			"":"",		
			"":"",		
			"":"",		
			"":"",					
			"":"",		
			"":"",		
			"":"",		
			"":"",		
			"":"",		
			"":"",		
			"":"",		
			"":"",		
			"":"",					
			"":"",		
			"":"",		
			"":"",		
			"":"",		
			"":"",		
			"":"",		
			"":"",		
			"":"",	
			"":"",					
			"":"",		
			"":"",		
			"":"",		
			"":"",		
			"":"",		
			"":"",		
			"":"",		
			"":"",		
			"":"",					
			"":"",		
			"":"",		
			"":"",		
			"":"",		
			"":"",		
			"":"",		
			"":"",		
			"":"",		
			"":"",					
			"":"",		
			"":"",		
			"":"",		
			"":"",		
			"":"",		
			"":"",		
			"":"",		
			"":"",	
			"":"",					
			"":"",		
			"":"",		
			"":"",		
			"":"",		
			"":"",		
			"":"",		
			"":"",		
			"":"",		
			"":"",					
			"":"",		
			"":"",		
			"":"",		
			"":"",		
			"":"",		
			"":"",		
			"":"",		
			"":"",		
			"":"",					
			"":"",		
			"":"",		
			"":"",		
			"":"",		
			"":"",		
			"":"",		
			"":"",		
			"":"",	
			"":"",					
			"":"",		
			"":"",		
			"":"",		
			"":"",		
			"":"",		
			"":"",		
			"":"",		
			"":"",		
			"":"",					
			"":"",		
			"":"",		
			"":"",		
			"":"",		
			"":"",		
			"":"",		
			"":"",		
			"":"",		
			"":"",					
			"":"",		
			"":"",		
			"":"",		
			"":"",		
			"":"",		
			"":"",		
			"":"",		
			"":"",	
			"":"",					
			"":"",		
			"":"",		
			"":"",		
			"":"",		
			"":"",		
			"":"",		
			"":"",		
			"":"",		
			"":"",					
			"":"",		
			"":"",		
			"":"",		
			"":"",		
			"":"",		
			"":"",		
			"":"",		
			"":"",		
			"":"",					
			"":"",		
			"":"",		
			"":"",		
			"":"",		
			"":"",		
			"":"",		
			"":"",		
			"":"",					
			"customize": "CUSTOMIZE"
        },
        "pt-br": {
            "login": "Login",
            "username": "Nome do usuário",
			"language": "Linguagem",
			"movies": "<b>FILMES</b>",
			"title": "Gerador de Histórias 1.4",
			"myname": "Criado por Prof. Paulo Alceu Rezende - 2021/2026",
			"starwars": "Guerra nas Estrelas",
			"lordofrings": "SENHOR DOS ANEIS",
			"matrix": "MATRIX",
			"harrypotter": "HARRYPOTTER",
			"lionking": "REI LEAO",
			"tail": "CRIAR CONTO",
			"scenes": "<b>CENAS</b>",
			"references": "REFERENCIAS",
			"over": "FALCAO, O CAMPEAO DOS CAMPEOES",
			"realsteel": "GIGANTES DE AÇO",
			"pointbreak": "CAÇADORES DE EMOÇÃO",
			"fastandfurious1":"VELOZES E FURIOSOS 1",
			"catjouney":"JORNADA DO GATO",
			"herojouney":"JORNADA DO HEROI",
			"savethecat":"SALVE O GATO",
			"act1":"ATO 1 (INICIAL E CONFLITO)",
			"Smurfette":"Efeito Smurfette (apenas uma protagonista feminina)",
			"Class":"Classe",	
			"act2":"ATO 2 (DESENVOLVIMENTO)",			
			"act3":"ATO 3 (CLIMAX)",	
			"act4":"ATO 4 (DESFECHO)",		
			"PLOTS_TYPES":"<b>TIPOS DE ENREDO</b>",			
			"DUCKLING":"O PATINHO FEIO",		
			"THEWIZARDOFOZ":"O MÁGICO DE OZ",		
			"NEMO":"PRCURANDO NEMO",		
			"ALICE":"ALICE NO PAÍS DAS MARAVILHAS",		
			"GULLIVERS":"AS VIAGENS DE GULLIVERS",		
			"PINOCCHIO":"PINOQUIO",		
			"MIDSUMMER":"SONHO DE UMA NOITE DE VERÃO",		
			"BRIDGET":"DIARIO DE BRIDGET JONES",		
			"MACBETH":"MACBETH",		
			"ROMEO":"Romeu e Julieta",		
			"BREAKING":"BREAKING BAD",		
			"SLEEPING":"A BELA ADORMECIDA",					
			"BEAST":"A BELA E A FERRA",		
			"MONSTER":"Superar o Monstro",		
			"MISERY":"Da Miséria a Riqueza",		
			"ALICE":"Alice no País das Maravilhas",		
			"Busca":"A Busca",		
			"Viagem":"Viagem e Retorno",		
			"KINGKONG":"King Kong",		
			"":"",		
			"":"",					
			"":"",		
			"":"",		
			"":"",		
			"":"",		
			"":"",		
			"":"",		
			"":"",		
			"":"",		
			"":"",					
			"":"",		
			"":"",		
			"":"",		
			"":"",		
			"":"",		
			"":"",		
			"":"",		
			"":"",		
			"":"",					
			"":"",		
			"":"",		
			"":"",		
			"":"",		
			"":"",		
			"":"",		
			"":"",		
			"":"",		
			"":"",					
			"":"",		
			"":"",		
			"":"",		
			"":"",		
			"":"",		
			"":"",		
			"":"",		
			"":"",		
			"":"",					
			"":"",		
			"":"",		
			"":"",		
			"":"",		
			"":"",		
			"":"",		
			"":"",		
			"":"",	
			"":"",					
			"":"",		
			"":"",		
			"":"",		
			"":"",		
			"":"",		
			"":"",		
			"":"",		
			"":"",		
			"":"",					
			"":"",		
			"":"",		
			"":"",		
			"":"",		
			"":"",		
			"":"",		
			"":"",		
			"":"",		
			"":"",					
			"":"",		
			"":"",		
			"":"",		
			"":"",		
			"":"",		
			"":"",		
			"":"",		
			"":"",	
			"":"",					
			"":"",		
			"":"",		
			"":"",		
			"":"",		
			"":"",		
			"":"",		
			"":"",		
			"":"",		
			"":"",					
			"":"",		
			"":"",		
			"":"",		
			"":"",		
			"":"",		
			"":"",		
			"":"",		
			"":"",		
			"":"",					
			"":"",		
			"":"",		
			"":"",		
			"":"",		
			"":"",		
			"":"",		
			"":"",		
			"":"",	
			"":"",					
			"":"",		
			"":"",		
			"":"",		
			"":"",		
			"":"",		
			"":"",		
			"":"",		
			"":"",		
			"":"",					
			"":"",		
			"":"",		
			"":"",		
			"":"",		
			"":"",		
			"":"",		
			"":"",		
			"":"",		
			"":"",					
			"":"",		
			"":"",		
			"":"",		
			"":"",		
			"":"",		
			"":"",		
			"":"",		
			"":"",	
			"":"",					
			"":"",		
			"":"",		
			"":"",		
			"":"",		
			"":"",		
			"":"",		
			"":"",		
			"":"",		
			"":"",					
			"":"",		
			"":"",		
			"":"",		
			"":"",		
			"":"",		
			"":"",		
			"":"",		
			"":"",		
			"":"",					
			"":"",		
			"":"",		
			"":"",		
			"":"",		
			"":"",		
			"":"",		
			"":"",		
			"":"",	
			"":"",					
			"":"",		
			"":"",		
			"":"",		
			"":"",		
			"":"",		
			"":"",		
			"":"",		
			"":"",		
			"":"",					
			"":"",		
			"":"",		
			"":"",		
			"":"",		
			"":"",		
			"":"",		
			"":"",		
			"":"",		
			"":"",					
			"":"",		
			"":"",		
			"":"",		
			"":"",		
			"":"",		
			"":"",		
			"":"",		
			"":"",	
			"":"",					
			"":"",		
			"":"",		
			"":"",		
			"":"",		
			"":"",		
			"":"",		
			"":"",		
			"":"",		
			"":"",					
			"":"",		
			"":"",		
			"":"",		
			"":"",		
			"":"",		
			"":"",		
			"":"",		
			"":"",		
			"":"",					
			"":"",		
			"":"",		
			"":"",		
			"":"",		
			"":"",		
			"":"",		
			"":"",		
			"":"",				
			"customize": "PERSONALIZAR"
        }
    };
	
function mudaliguagem(valor){
var language = valor.toLowerCase();
var divs = document.getElementsByTagName("label");
	for (var key in dictionary[language]) {
		var procura = dictionary[language][key];
		var substitui = key;
		for (i = 0; i < divs.length; ++i) {
			if (divs[i].classList.contains(substitui)) {
			divs[i].innerHTML = procura;
			}
		}	
	}
}